sudo: required
language: generic 


services: 
  - docker

before_install:
  - docker build -t kaushikred/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kaushikred/docker-react npm run test