sudo: required
language: generic 


services: 
  - docker

before_install:
  - docker build -t kaushikred/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kaushikred/docker-react npm run test

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-393566365858"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY